package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
  "log"
  "os"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHandlerFunc turns a function with the right signature into a get handler
type GetHandlerFunc func(GetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHandlerFunc) Handle(params GetParams) middleware.Responder {
	return fn(params)
}

// GetHandler interface for that can handle valid get params
type GetHandler interface {
	Handle(GetParams) middleware.Responder
}

// NewGet creates a new http.Handler for the get operation
func NewGet(ctx *middleware.Context, handler GetHandler) *Get {
	return &Get{Context: ctx, Handler: handler}
}

/*Get swagger:route GET / get

Get in touch with the deathstar

*/
type Get struct {
	Context *middleware.Context
	Handler GetHandler
}

func (o *Get) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	var Params = NewGetParams()

	f, err := os.OpenFile("request.log", os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
					log.Fatal(err)
	}   

	//defer to close when you're done with it, not because you think it's idiomatic!
	defer f.Close()

	//set output of logs to f
	log.SetOutput(f)

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
    log.Printf("%s %s", Params.HTTPRequest.Method, Params.HTTPRequest.URL)
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

  log.Printf("%s %s", Params.HTTPRequest.Method, Params.HTTPRequest.URL)
	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
